### ISSUE TITLE
Edit Assigned Slides for Presentation

### ISSUE THREAD

**Issue by pwfoote** [pwfoote/FanBook.com#10]
Slides are available in Slides Doc.

Edit assigned slide content to your desire to be comfortable with your part of  the presentation.

https://docs.google.com/presentation/d/1tGo2_yHXr9yHZTUQkKZYvk-eZ6kTEKa4gkFDqujj1R0/edit#slide=id.gcb9a0b074_1_0

**Comment by phopps** [comment]
Presentation went great, issue #10 closed
