### ISSUE TITLE
Test APIs

### ISSUE THREAD

**Issue by pwfoote** [pwfoote/FanBook.com#2]
In JS:
-write code that can search through Music Brains API to find Artist Profile
-write code that can search through Disogs to find Artist Profile

**Comment by pwfoote** [comment]
updated API selections to Music Brains and Discogs

**Comment by phopps** [comment]
APIs have been tested and we have simplified the search process to just MusicBrainz API to suggest artist spelling in autocomplete, and Discogs to return artist profile info
