### ISSUE TITLE
Criteria : Repository

### ISSUE THREAD

**Issue by phopps** [pwfoote/FanBook.com#28]
Have a clean repository that meets quality coding standards (file structure, naming conventions, follows best practices for class/id-naming conventions, indentation, quality comments, etc.).

**Comment by phopps** [comment]
- [x] Add comments to code
- [x] Clean code formatting (spacing, spelling, etc.)
- [x] Remove unneeded code
- [x] Clean up all github issues, comments, etc.

**Comment by pwfoote** [comment]
boom
