### ISSUE TITLE
Develop MVP

### ISSUE THREAD

**Issue by pwfoote** [pwfoote/FanBook.com#5]
Code Name : **ChampangePapi**

Minimum Viable Product:
As A USER
WHEN I visit FanBook.com I am 
GIVEN a website to search my favorite Music Artist
THAT prompts me to search my favorite Music Artist
WHEN I search a chosen Artist
THEN I am presented with links to Artist's pages on MusicBrainz and Discogs
THAT will generate to the WebPage

**Comment by Tyreezew** [comment]
We have to update the Instagram and Spotify links to MusicBrainz.org and Discogs.com due to third party authentication issues.

**Comment by Tyreezew** [comment]
Updated links to MusicBrainz and Discog
