### ISSUE TITLE
css bug (feature/html-mvp branch)

### ISSUE THREAD

**Issue by Isaaccna** [pwfoote/FanBook.com#8]
Current behavior : 
- The body's background color has been applied only on the top of the page where there is content.

Expected behavior :
- The body's background color has to be applied on the whole page.

**Comment by pwfoote** [comment]
can you send a screen shot to the group chat? just for visual aid.

also: if this is a bulma issue, you will have to add "has-background-primary" to each individual html component. ie, header, body, footer etc.

**Comment by phopps** [comment]
Before:
![fanbook-issue-08-before](https://user-images.githubusercontent.com/6439587/141869755-4025c13e-0a10-4735-9241-4ed6d55a1174.png)

After:
![fanbook-issue-08-after](https://user-images.githubusercontent.com/6439587/141869753-b2d68a93-764b-4e24-830c-97fe0bce9e75.png)

**Comment by pwfoote** [comment]
this looks good, colors look sharp. good job issac.

**Comment by phopps** [comment]
[added class has-background-grey-light to top of html, closes issue #8](https://github.com/pwfoote/FanBook.com/commit/a4b0086a63f795a756acc18b3ace3480e810bf34)
